version: '2.2'

networks:
  bonitaNetwork:
volumes:
  data_psql:

services:
  posgresql:
    image: postgres:9.3
    container_name: postgresql
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres.conf:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
      - data_psql:/var/lib/postgresql/data
    networks:
      - bonitaNetwork

  bonita:
    image: bonita:7.8
    container_name: bonita
    ports: 
      - "8080:8080"
    environment:
      TENANT_LOGIN: ${TENANT_LOGIN} 
      TENANT_PASSWORD: ${TENANT_PASSWORD}
      PLATFORM_LOGIN: ${PLATFORM_LOGIN}
      PLATFORM_PASSWORD: ${PLATFORM_PASSWORD}
      DB_VENDOR: ${DB_VENDOR}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASS: ${DB_ADMIN_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      BIZ_DB_NAME: ${BIZ_DB_NAME}
      BIZ_DB_USER: ${BIZ_DB_USER}
      BIZ_DB_PASS: ${BIZ_DB_PASS}
    networks:
      - bonitaNetwork
    depends_on:
      - posgresql


